[package]
name = "sqlite-vec"
version = "0.0.1-alpha.3"
license = "MIT OR Apache"
homepage = "https://alexgarcia.xyz/sqlite-vec"
repo = "https://github.com/asg017/sqlite-vec"
description = "A vector search SQLite extension."
authors = ["Alex Garcia"]

[targets]
github_releases = {}
sqlpkg = {}
spm = {}

pip = {}
datasette = {}
sqlite_utils = {}

npm = {}

gem = { module_name = "SqliteVec" }
